/*
 * Copyright 2026 Everypin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "i2c_bus.h"

#include <stm32g0xx_hal.h>

/// Defaults applied on power-on and by *RST
#define I2C_BUS_FREQ_DEFAULT    100000
#define I2C_BUS_TIMEOUT_DEFAULT 100

/// Supported range of the transaction timeout in milliseconds
#define I2C_BUS_TIMEOUT_MIN 1
#define I2C_BUS_TIMEOUT_MAX 10000

/// Max unshifted address of a slave, per width of the address
#define I2C_BUS_ADDR_MAX_7BIT  0x7F
#define I2C_BUS_ADDR_MAX_10BIT 0x3FF

/// Number of clock pulses generated by a recovery of the bus
#define I2C_BUS_RECOVER_PULSES 9

/// Iterations of the busy wait of a half period of the recovery clock. The
/// loop is a few cycles long at 64 MHz, which puts the recovery clock in the
/// tens of kilohertz - a slave releases SDA on any clock slow enough to meet
/// the bus timing, so the exact value does not matter.
#define I2C_BUS_RECOVER_DELAY_LOOPS 40

/**
 * Pins of the bus on the external connector, they are dedicated to it and are
 * not shared with the GPIO subsystem. The labels of the board are I2C2_SCL
 * and I2C2_SDA.
 */
#define I2C2_SCL_GPIO_Port GPIOA
#define I2C2_SCL_Pin       GPIO_PIN_7
#define I2C2_SDA_GPIO_Port GPIOB
#define I2C2_SDA_Pin       GPIO_PIN_4

/// Clock setup of the peripheral for a supported frequency
typedef struct
{
    uint32_t hz;
    uint32_t timing;
} I2cBusSpeed;

/// Current configuration of the bus
typedef struct
{
    bool            enabled;
    uint32_t        freq_hz;
    uint32_t        addr;
    I2cBusAddrWidth width;
    bool            pullup;
    uint32_t        timeout_ms;
} I2cBusCfg;

/**
 * Supported clock frequencies, in ascending order, with the TIMINGR value of
 * the peripheral for each one. I2C2 is clocked from PCLK1 at 64 MHz, so a
 * prescaled tick is t_PRESC = (PRESC + 1) / 64 MHz and the period of the
 * clock is (SCLL + 1 + SCLH + 1) * t_PRESC plus the rise and fall times.
 *
 * The 100 kHz entry is the value CubeMX generated for MX_I2C2_Init(), it is
 * the reference of the table: PRESC = 1, SCLDEL = 0xB, SDADEL = 1, SCLH = 125,
 * SCLL = 181, that is 126 * 31.25 ns high and 182 * 31.25 ns low.
 *
 * The other two are derived with the same formula for a rise time of 100 ns
 * and a fall time of 10 ns, keeping the data setup time above the 250 ns of
 * standard mode and the 100 ns of fast mode. They have not been measured on
 * hardware yet - check them on a scope before trusting the edges.
 */
static const I2cBusSpeed SPEEDS[] = {
    {10000,  0xC042F5F5}, // PRESC=0xC SCLDEL=4 SDADEL=2 SCLH=0xF5 SCLL=0xF5
    {100000, 0x10B17DB5}, // PRESC=1   SCLDEL=B SDADEL=1 SCLH=0x7D SCLL=0xB5
    {400000, 0x00924453}, // PRESC=0   SCLDEL=9 SDADEL=2 SCLH=0x44 SCLL=0x53
};

#define I2C_BUS_SPEED_COUNT (sizeof(SPEEDS) / sizeof(SPEEDS[0]))

extern I2C_HandleTypeDef hi2c2;

static I2cBusCfg cfg;

/**
 * @brief Get the TIMINGR value of the current frequency.
 *
 * @return uint32_t Value of the register.
 */
static uint32_t i2c_bus_timing(void)
{
    for (uint32_t index = 0; index < I2C_BUS_SPEED_COUNT; index++) {
        if (SPEEDS[index].hz == cfg.freq_hz) {
            return SPEEDS[index].timing;
        }
    }

    return SPEEDS[0].timing;
}

/**
 * @brief Get the address of the slave in the form expected by the HAL.
 *
 * A 7 bit address sits in SADD[7:1] of the peripheral, so it is shifted, a
 * 10 bit one fills SADD[9:0] and is passed as it is.
 *
 * @return uint16_t Address of the slave.
 */
static uint16_t i2c_bus_dev_addr(void)
{
    if (cfg.width == I2C_BUS_WIDTH_10BIT) {
        return (uint16_t)cfg.addr;
    }

    return (uint16_t)(cfg.addr << 1);
}

/**
 * @brief Convert a result of the HAL into a status of the bus.
 *
 * @param status Result of the call of the HAL.
 * @return I2cBusStatus Status of the bus.
 */
static I2cBusStatus i2c_bus_status(HAL_StatusTypeDef status)
{
    if (status == HAL_OK) {
        return I2C_BUS_OK;
    }

    const uint32_t error = HAL_I2C_GetError(&hi2c2);

    if ((error & HAL_I2C_ERROR_AF) != 0) {
        return I2C_BUS_ERR_NACK;
    }

    if ((status == HAL_TIMEOUT) || ((error & HAL_I2C_ERROR_TIMEOUT) != 0)) {
        return I2C_BUS_ERR_TIMEOUT;
    }

    return I2C_BUS_ERR_BUS;
}

/**
 * @brief Apply the pull resistor setup to SDA and SCL.
 *
 * The pins keep the alternate function of the peripheral and the open drain
 * driver, only the pull resistor changes.
 */
static void i2c_bus_pullup_apply(void)
{
    GPIO_InitTypeDef init = {0};

    init.Mode      = GPIO_MODE_AF_OD;
    init.Speed     = GPIO_SPEED_FREQ_LOW;
    init.Alternate = GPIO_AF8_I2C2;
    init.Pull      = cfg.pullup ? GPIO_PULLUP : GPIO_NOPULL;

    init.Pin = I2C2_SCL_Pin;
    HAL_GPIO_Init(I2C2_SCL_GPIO_Port, &init);

    init.Pin = I2C2_SDA_Pin;
    HAL_GPIO_Init(I2C2_SDA_GPIO_Port, &init);
}

/**
 * @brief Apply the stored configuration to the peripheral.
 *
 * @return I2cBusStatus I2C_BUS_ERR_BUS if the hardware rejected the setup.
 */
static I2cBusStatus i2c_bus_apply(void)
{
    HAL_I2C_DeInit(&hi2c2);

    hi2c2.Instance              = I2C2;
    hi2c2.Init.Timing           = i2c_bus_timing();
    hi2c2.Init.OwnAddress1      = 0;
    hi2c2.Init.AddressingMode   = (cfg.width == I2C_BUS_WIDTH_10BIT) ?
                                      I2C_ADDRESSINGMODE_10BIT :
                                      I2C_ADDRESSINGMODE_7BIT;
    hi2c2.Init.DualAddressMode  = I2C_DUALADDRESS_DISABLE;
    hi2c2.Init.OwnAddress2      = 0;
    hi2c2.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c2.Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c2.Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;

    if (HAL_I2C_Init(&hi2c2) != HAL_OK) {
        return I2C_BUS_ERR_BUS;
    }

    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c2, I2C_ANALOGFILTER_ENABLE) !=
        HAL_OK) {
        return I2C_BUS_ERR_BUS;
    }

    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c2, 0) != HAL_OK) {
        return I2C_BUS_ERR_BUS;
    }

    // The init of the HAL reconfigures the pins, so the pull resistors are
    // restored after it
    i2c_bus_pullup_apply();

    return I2C_BUS_OK;
}

/**
 * @brief Re-apply the stored configuration if the bus is enabled.
 *
 * @return I2cBusStatus Result of the setup.
 */
static I2cBusStatus i2c_bus_refresh(void)
{
    if (!cfg.enabled) {
        return I2C_BUS_OK;
    }

    return i2c_bus_apply();
}

void i2c_bus_init(void)
{
    // The recovery drives SDA and SCL directly, so their port clocks have to
    // stay on even while the peripheral is released
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    i2c_bus_reset();
}

void i2c_bus_reset(void)
{
    cfg.enabled    = false;
    cfg.freq_hz    = I2C_BUS_FREQ_DEFAULT;
    cfg.addr       = 0;
    cfg.width      = I2C_BUS_WIDTH_7BIT;
    cfg.pullup     = false;
    cfg.timeout_ms = I2C_BUS_TIMEOUT_DEFAULT;

    // The peripheral is brought up by the setup of the board, so a disabled
    // bus has to be released rather than just left alone
    HAL_I2C_DeInit(&hi2c2);
}

I2cBusStatus i2c_bus_state_set(bool enabled)
{
    if (enabled == cfg.enabled) {
        return I2C_BUS_OK;
    }

    if (!enabled) {
        cfg.enabled = false;
        HAL_I2C_DeInit(&hi2c2);
        return I2C_BUS_OK;
    }

    const I2cBusStatus status = i2c_bus_apply();
    if (status != I2C_BUS_OK) {
        HAL_I2C_DeInit(&hi2c2);
        return status;
    }

    cfg.enabled = true;
    return I2C_BUS_OK;
}

bool i2c_bus_state_get(void)
{
    return cfg.enabled;
}

I2cBusStatus i2c_bus_freq_set(uint32_t hz)
{
    for (uint32_t index = 0; index < I2C_BUS_SPEED_COUNT; index++) {
        if (SPEEDS[index].hz != hz) {
            continue;
        }

        cfg.freq_hz = hz;
        return i2c_bus_refresh();
    }

    return I2C_BUS_ERR_PARAM;
}

uint32_t i2c_bus_freq_get(void)
{
    return cfg.freq_hz;
}

uint32_t i2c_bus_freq_min_get(void)
{
    return SPEEDS[0].hz;
}

uint32_t i2c_bus_freq_max_get(void)
{
    return SPEEDS[I2C_BUS_SPEED_COUNT - 1].hz;
}

void i2c_bus_addr_set(uint32_t addr)
{
    if (addr > i2c_bus_addr_max_get()) {
        return;
    }

    cfg.addr = addr;
}

uint32_t i2c_bus_addr_get(void)
{
    return cfg.addr;
}

I2cBusStatus i2c_bus_addr_width_set(I2cBusAddrWidth width)
{
    cfg.width = width;

    // A narrower address cannot keep a value of the wider one
    if (cfg.addr > i2c_bus_addr_max_get()) {
        cfg.addr = 0;
    }

    return i2c_bus_refresh();
}

I2cBusAddrWidth i2c_bus_addr_width_get(void)
{
    return cfg.width;
}

uint32_t i2c_bus_addr_max_get(void)
{
    if (cfg.width == I2C_BUS_WIDTH_10BIT) {
        return I2C_BUS_ADDR_MAX_10BIT;
    }

    return I2C_BUS_ADDR_MAX_7BIT;
}

I2cBusStatus i2c_bus_pullup_set(bool enabled)
{
    cfg.pullup = enabled;

    if (cfg.enabled) {
        i2c_bus_pullup_apply();
    }

    return I2C_BUS_OK;
}

bool i2c_bus_pullup_get(void)
{
    return cfg.pullup;
}

void i2c_bus_timeout_set(uint32_t ms)
{
    if (ms < I2C_BUS_TIMEOUT_MIN) {
        ms = I2C_BUS_TIMEOUT_MIN;
    }
    else if (ms > I2C_BUS_TIMEOUT_MAX) {
        ms = I2C_BUS_TIMEOUT_MAX;
    }

    cfg.timeout_ms = ms;
}

uint32_t i2c_bus_timeout_get(void)
{
    return cfg.timeout_ms;
}

uint32_t i2c_bus_timeout_min_get(void)
{
    return I2C_BUS_TIMEOUT_MIN;
}

uint32_t i2c_bus_timeout_max_get(void)
{
    return I2C_BUS_TIMEOUT_MAX;
}

I2cBusStatus i2c_bus_write(const uint8_t* data, uint32_t len)
{
    if (!cfg.enabled) {
        return I2C_BUS_ERR_DISABLED;
    }

    if (len == 0 || len > I2C_BUS_XFER_MAX_LEN) {
        return I2C_BUS_ERR_PARAM;
    }

    const HAL_StatusTypeDef status = HAL_I2C_Master_Transmit(
        &hi2c2,
        i2c_bus_dev_addr(),
        (uint8_t*)data,
        (uint16_t)len,
        cfg.timeout_ms
    );

    return i2c_bus_status(status);
}

I2cBusStatus i2c_bus_read(uint8_t* dst, uint32_t count)
{
    if (!cfg.enabled) {
        return I2C_BUS_ERR_DISABLED;
    }

    if (count == 0 || count > I2C_BUS_XFER_MAX_LEN) {
        return I2C_BUS_ERR_PARAM;
    }

    const HAL_StatusTypeDef status = HAL_I2C_Master_Receive(
        &hi2c2, i2c_bus_dev_addr(), dst, (uint16_t)count, cfg.timeout_ms
    );

    return i2c_bus_status(status);
}

I2cBusStatus i2c_bus_transfer(
    const uint8_t* prefix, uint32_t prefix_len, uint8_t* dst, uint32_t count
)
{
    if (!cfg.enabled) {
        return I2C_BUS_ERR_DISABLED;
    }

    if (count == 0 || count > I2C_BUS_XFER_MAX_LEN) {
        return I2C_BUS_ERR_PARAM;
    }

    if (prefix_len == 0 || prefix_len > I2C_BUS_PREFIX_MAX_LEN) {
        return I2C_BUS_ERR_PARAM;
    }

    // The blocking HAL carries the write phase of a repeated start in the
    // memory address of a read, the first byte goes on the wire first
    uint16_t mem_addr = prefix[0];
    uint16_t mem_size = I2C_MEMADD_SIZE_8BIT;

    if (prefix_len == 2) {
        mem_addr = (uint16_t)((prefix[0] << 8) | prefix[1]);
        mem_size = I2C_MEMADD_SIZE_16BIT;
    }

    const HAL_StatusTypeDef status = HAL_I2C_Mem_Read(
        &hi2c2,
        i2c_bus_dev_addr(),
        mem_addr,
        mem_size,
        dst,
        (uint16_t)count,
        cfg.timeout_ms
    );

    return i2c_bus_status(status);
}

/**
 * @brief Busy wait of a half period of the clock of a recovery.
 */
static void i2c_bus_recover_delay(void)
{
    for (volatile uint32_t loop = 0; loop < I2C_BUS_RECOVER_DELAY_LOOPS;
         loop++) {}
}

I2cBusStatus i2c_bus_recover(void)
{
    GPIO_InitTypeDef init = {0};

    // The peripheral cannot drive the pins while they are bit banged
    HAL_I2C_DeInit(&hi2c2);

    init.Mode  = GPIO_MODE_OUTPUT_OD;
    init.Pull  = GPIO_NOPULL;
    init.Speed = GPIO_SPEED_FREQ_LOW;
    init.Pin   = I2C2_SCL_Pin;
    HAL_GPIO_Init(I2C2_SCL_GPIO_Port, &init);

    init.Mode = GPIO_MODE_INPUT;
    init.Pin  = I2C2_SDA_Pin;
    HAL_GPIO_Init(I2C2_SDA_GPIO_Port, &init);

    HAL_GPIO_WritePin(I2C2_SCL_GPIO_Port, I2C2_SCL_Pin, GPIO_PIN_SET);
    i2c_bus_recover_delay();

    for (uint32_t pulse = 0; pulse < I2C_BUS_RECOVER_PULSES; pulse++) {
        if (HAL_GPIO_ReadPin(I2C2_SDA_GPIO_Port, I2C2_SDA_Pin) ==
            GPIO_PIN_SET) {
            break;
        }

        HAL_GPIO_WritePin(I2C2_SCL_GPIO_Port, I2C2_SCL_Pin, GPIO_PIN_RESET);
        i2c_bus_recover_delay();
        HAL_GPIO_WritePin(I2C2_SCL_GPIO_Port, I2C2_SCL_Pin, GPIO_PIN_SET);
        i2c_bus_recover_delay();
    }

    // Manual stop condition, SDA is released while SCL is high
    init.Mode = GPIO_MODE_OUTPUT_OD;
    init.Pin  = I2C2_SDA_Pin;
    HAL_GPIO_Init(I2C2_SDA_GPIO_Port, &init);

    HAL_GPIO_WritePin(I2C2_SDA_GPIO_Port, I2C2_SDA_Pin, GPIO_PIN_RESET);
    i2c_bus_recover_delay();
    HAL_GPIO_WritePin(I2C2_SDA_GPIO_Port, I2C2_SDA_Pin, GPIO_PIN_SET);
    i2c_bus_recover_delay();

    const bool released =
        HAL_GPIO_ReadPin(I2C2_SDA_GPIO_Port, I2C2_SDA_Pin) == GPIO_PIN_SET;

    if (cfg.enabled) {
        const I2cBusStatus status = i2c_bus_apply();
        if (status != I2C_BUS_OK) {
            return status;
        }
    }
    else {
        // A disabled bus leaves the pins released, the way the deinit of the
        // peripheral does
        HAL_GPIO_DeInit(I2C2_SCL_GPIO_Port, I2C2_SCL_Pin);
        HAL_GPIO_DeInit(I2C2_SDA_GPIO_Port, I2C2_SDA_Pin);
    }

    return released ? I2C_BUS_OK : I2C_BUS_ERR_BUS;
}
